apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m6o9154hs-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9eee019217.n2dw.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:7b550d87cac579d1a72d9641e2b6b196a14e2a32@sha256:336390c25533bd6883ae62c1b85a7989fa7039d698f884310dbc12b3e0900787
          name: container-image
